fragment BookDetails on Book {
  id
  title
  authors
  genre
  summary
  imageUrl
  publishedDate
  content
}

query Books @auth(level: PUBLIC) {
  books {
    ...BookDetails
  }
}

query ReadHistory($uid: String!) @auth(expr: "auth.uid == uid") {
  readHistories(where: { userUid: { eq: $uid } }) {
    id
    book {
      ...BookDetails
    }
    readDate
    rating
    review
    user {
      uid
      name
      email
    }
  }
}

query Recommendations($uid: String!) @auth(expr: "auth.uid == uid") {
  recommendations(where: { userUid: { eq: $uid } }) {
    id
    book {
      ...BookDetails
    }
    reason
    createdAt
  }
}
