extend type ReadHistory {
  """
  ✨ Implicit foreign key field based on `ReadHistory`.`book`. It must match the value of `Book`.`id`. See `@ref` for how to customize it.
  """
  bookId: UUID! @fdc_generated(from: "ReadHistory.book", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `ReadHistory`.`user`. It must match the value of `User`.`uid`. See `@ref` for how to customize it.
  """
  userUid: String! @fdc_generated(from: "ReadHistory.user", purpose: IMPLICIT_REF_FIELD)
}
