type User @table(key: "uid") {
  uid: String! @default(expr: "auth.uid")
  email: String! @unique
  name: String
  createdAt: Timestamp! @default(expr: "request.time")
  updatedAt: Timestamp! @default(expr: "request.time")
}

type Book @table(key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  title: String!
  imageUrl: String!
  summary: String!
  genre: [String!]!
  authors: [String!]!
  publishedDate: Timestamp!
  content: String! @default(value: "")
  contentEmbed: Vector! @col(size: 768)
}

type ReadHistory @table(key: ["user", "id"]) {
  id: UUID! @default(expr: "uuidV4()")
  book: Book!
  user: User!
  readDate: Timestamp! @default(expr: "request.time")
  rating: Int
  review: String
  createdAt: Timestamp! @default(expr: "request.time")
}
